### ISSUE TITLE
Checking fullfilled appointments

### ISSUE THREAD

**Issue by vallu** [ExLibrisGroup/alma-scheduler#14]
Checking fulfilled appointments, in order to know those unfulfilled, and contact the user or delete them if necessary. Maybe this can be done by adding a checkbox to the appointment, or exporting the appointments of the day to a file, and check that list manually.

Thank you very much.

**Comment by jweisman** [comment]
Hi @vallu . I'm not 100% clear on the use case here, but we added a print button at the bottom of the calendar. Let us know if this is helpful to you.

**Comment by jweisman** [comment]
Hope this helped. If not, feel free to reopen this issue.

**Comment by vallu** [comment]
Hello Josh,
Sorry for not answering before. Yes, printing the scheduled appointments
for a day helps checking those that came to the library and deleting the
appointments of those that didn't come, so we have a better picture of the
appointments fulfilled.
We are now using the Appointment Scheduler in many of our libraries, and
specially those that have more appointments to deal with, and it is working
very well.
Thank you very much!!

FRANCISCO JOSÉ SÁENZ DE VALLUERCA LÓPEZ

Universidad de Salamanca
Servicio de Bibliotecas
Área de Normalización, Automatización y Proceso Técnico
Campus Miguel de Unamuno s.n.
37007 - Salamanca
tel.: +34 677524194; +34 923 294500 ext:1221
email: vallu@usal.es

**Comment by jweisman** [comment]
Great to hear! Thanks for the feedback.
