### ISSUE TITLE
Additional time slots

### ISSUE THREAD

**Issue by AxelDorian** [ExLibrisGroup/alma-scheduler#15]
Would it be possible to add additional time slots to the general configuration such as:

1 hour
2 hours
5 hours
1 day

Thanks a lot
Bruce Sciboz

**Comment by jweisman** [comment]
Hi @AxelDorian - we have released a new minor version with these updated slots. Let us know how it works for you.

**Comment by AxelDorian** [comment]
Hi @jweisman 
It looks promising. Thanks a lot for your promptness!

**Comment by jweisman** [comment]
Good to hear- thanks for the feedback.
