### ISSUE TITLE
Appointment Scheduler - Primo VE Add-On 

### ISSUE THREAD

**Issue by AxelDorian** [ExLibrisGroup/alma-scheduler#16]
Hi,
I tried to follow your procedure to add a widget in Primo VE account but I received a "Cannot communicate with scheduler service" error message from the Account Overview window.

According to the console : Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-eu.exldevnetwork.net/alma-scheduler/patron/config:1 GET https://api-eu.exldevnetwork.net/alma-scheduler/patron/config 401 (Unauthorized)

However I checked my API key and it seems to be correctky set.

What am I missing?

Thanks for your help.

Kind regards,
Bruce

**Comment by jweisman** [comment]
Hi. Thanks for trying out this brand new feature! 

In order to figure out what's happening, it would be great if you could go into the "Network" tab in the Developer Tools (next to the Console), find the config request which failed, right click, and select Copy as cURL. Then paste the results in this issue. Don't worry- there's no sensitive information there.

Let me know if you have trouble finding the options in your browser.

![Screen Shot 2021-02-16 at 18 55 48 ](https://user-images.githubusercontent.com/80420/108095963-1af49880-7089-11eb-83fd-c75615244a7a.png)

**Comment by AxelDorian** [comment]
Hi, here you go:

curl "https://api-eu.exldevnetwork.net/alma-scheduler/patron/config" -H "Accept: application/json, text/plain, */*" -H "Referer: https://nb-helveticat-psb.primo.exlibrisgroup.com/discovery/account?vid=41SNL_51_INST:helveticat^&section=overview^&lang=en" -H "Origin: https://nb-helveticat-psb.primo.exlibrisgroup.com" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" -H "X-Exl-Apikey: l8xx1f11851cd43d4ab792fb032ca9794d25" -H "Authorization: Bearer eyJraWQiOiJwcmltYVByaXZhdGVLZXktNDFTTkxfNTFfSU5TVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJQcmltYSIsImp0aSI6IkIxMzBBNDVFOTI4RTVGMzMwMENDMDJFMTlDMEE2QjVCLmFwcDAxLmV1MDAucHNiLmFsbWEuZGMwNi5ob3N0ZWQuZXhsaWJyaXNncm91cC5jb206MTgwMSIsImV4cCI6MTYxMzYyOTM4OCwiaWF0IjoxNjEzNTQyOTg4LCJ1c2VyTmFtZSI6InNjYnIiLCJkaXNwbGF5TmFtZSI6IlNjaWJveiwgQnJ1Y2UiLCJ1c2VyIjoiODE0Mjg4NDcwMDAzOTc2IiwidXNlckdyb3VwIjoiTkQiLCJpbnN0aXR1dGlvbiI6IjQxU05MXzUxX0lOU1QiLCJ1c2VySXAiOiIxNjIuMjMuMTExLjUwIiwiYXV0aGVudGljYXRpb25Qcm9maWxlIjoiQWxtYSIsImF1dGhlbnRpY2F0aW9uU3lzdGVtIjoiIiwibGFuZ3VhZ2UiOiJlbiIsInNhbWxTZXNzaW9uSW5kZXgiOiIiLCJzYW1sTmFtZUlkIjoiIiwib25DYW1wdXMiOiJmYWxzZSIsInNpZ25lZEluIjoidHJ1ZSIsInZpZXdJZCI6IjQxU05MXzUxX0lOU1Q6aGVsdmV0aWNhdCJ9.eIQJ2t_HTLjpC6WXHB_4dRI8z0UWSV-juPI_W7DwPPFVu7TU9F5u_ghPMDp7oqdlUga9O588hCLHnrUR2PPCQg" -H "Sec-Fetch-Mode: cors" --compressed

I hope it helps.
Kind Regards,
Bruce

**Comment by jweisman** [comment]
Thanks- this is helpful. Checking into it....

**Comment by jweisman** [comment]
Hey @jweisman - my colleague @ori229 looked at this and noticed that your sandbox routing in the Developer Network was not correct. We fixed that and are seeing better results. Can you check again from your side?

**Comment by AxelDorian** [comment]
Great! I took a quick look and was able to connect and add a new appointment 👍  Was it something that I did not defined correctly with the API key? Thanks a bunch. We are looking forward to testing this nice feature.

**Comment by jweisman** [comment]
Nothing on your side- it was a configuration issue on our side. Glad it's worked out now.
