### ISSUE TITLE
Primo VE: Cannot communicate with scheduler service

### ISSUE THREAD

**Issue by AxelDorian** [ExLibrisGroup/alma-scheduler#20]
Hi,
I have again a communication problem with the Scheduler Service on the Sandbox.
Since I've defined a new API key for the production env the scheduler service no longer works on the Sandbox
So far there a re 2 differents API keys for PSB and PROD and I updated the keys in the custom.js the accordingly 

Here is the the config request which failed :

curl "https://api-eu.exldevnetwork.net/alma-scheduler/patron/config" -H "Accept: application/json, text/plain, */*" -H "Referer: https://nb-helveticat-psb.primo.exlibrisgroup.com/discovery/account?vid=41SNL_51_INST:helveticat^&section=overview^&lang=fr" -H "Origin: https://nb-helveticat-psb.primo.exlibrisgroup.com" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36" -H "X-Exl-Apikey: l8xx1f11851cd43d4ab792fb032ca9794d25" -H "Authorization: Bearer eyJraWQiOiJwcmltYVByaXZhdGVLZXktNDFTTkxfNTFfSU5TVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJQcmltYSIsImp0aSI6Ijc2NkY0MTcxQjkzRkJEODZCMjMzMTQ1NkI0Mjk0NjM1LmFwcDAxLmV1MDAucHNiLmFsbWEuZGMwNi5ob3N0ZWQuZXhsaWJyaXNncm91cC5jb206MTgwMSIsImV4cCI6MTYxNzI2NDIyNiwiaWF0IjoxNjE3MTc3ODI2LCJ1c2VyTmFtZSI6InNjYnIiLCJkaXNwbGF5TmFtZSI6IlNjaWJveiwgQnJ1Y2UiLCJ1c2VyIjoiODE0Mjg4NDcwMDAzOTc2IiwidXNlckdyb3VwIjoiTkQiLCJpbnN0aXR1dGlvbiI6IjQxU05MXzUxX0lOU1QiLCJ1c2VySXAiOiIxNjIuMjMuMTExLjUzIiwiYXV0aGVudGljYXRpb25Qcm9maWxlIjoiQWxtYSIsImF1dGhlbnRpY2F0aW9uU3lzdGVtIjoiIiwibGFuZ3VhZ2UiOiJmciIsInNhbWxTZXNzaW9uSW5kZXgiOiIiLCJzYW1sTmFtZUlkIjoiIiwib25DYW1wdXMiOiJmYWxzZSIsInNpZ25lZEluIjoidHJ1ZSIsInZpZXdJZCI6IjQxU05MXzUxX0lOU1Q6aGVsdmV0aWNhdCJ9.bwC7UCT_GUUfZBo3CUwiONnvvozSYKjf-b4Ws8FttDbSTvb2IyglsyRfcGkpiRq7uxEmUD35TLWmWPhJXWmJww" -H "Sec-Fetch-Mode: cors" --compressed

In addition the Scheduler service from the Primo VE PROD env seems to be linked to Alma Sandbox even if I used the API key from the PROD. When adding a new reservation on Primo VE PROD the reservation is added to the Scheduler Service in Alma Sandbox.

Thanks for your help.

Kind regards,
Bruce

**Comment by jweisman** [comment]
Hi @AxelDorian . Thanks for your issue. We tried to make a change which would improve security but we see that it makes it impossible to use both sandbox and production at the same time. So we rolled back the change for now. Please give it a try again.

**Comment by AxelDorian** [comment]
Hi Josh, thanks. I overlooked this note in the documentation. Saving the configuration in the production Cloud App fixed the issue and the appointments are now registered in the production instance. We don't plan to use the scheduler in sandbox and production simultaneously so it should not be a problem. I'll go ahead and remove it from the Sandbox to avoid misuse.

**Comment by jweisman** [comment]
Great- glad that worked!
