### ISSUE TITLE
Add a replacement code for duration

### ISSUE THREAD

**Issue by bibnumbcu** [ExLibrisGroup/alma-scheduler#48]
Hi Josh!

I suggest to add a replacement code for duration in the notification. Since we can manage the duration of the appointment before confirming to the user, it would be nice for him to know how much time he has.
So is it possible to have {{duration}} in the notification configuration?

Thanks!
-Raphaële

**Comment by jweisman** [comment]
Hi @bibnumbcu - we added this in the [latest version](https://github.com/ExLibrisGroup/alma-scheduler/releases/tag/v0.3.4). Please let us know if it works for you.

**Comment by bibnumbcu** [comment]
Hi! Yes it works, thanks
