### ISSUE TITLE
How to integrate translated strings for Primo add-on?

### ISSUE THREAD

**Issue by bibnumbcu** [ExLibrisGroup/alma-scheduler#49]
Hi!

You say about the configuration parameters:

> Overrides for the strings used in the display. The list of string is available here. Any string not provided will fall-back to the default. Strings can be provided in different Primo locales (i.e. en, fr).
Example:

i18n='{
  en: {
    appointments: "Library Appointments"
  },
  fr: {
    appointments: "Rendez-vous à la bibliothèque"
  }
}'

In which file can we add strings in french?

thanks!
-Raphaële

**Comment by jweisman** [comment]
Hi @bibnumbcu - you can add these into the declaration of the template in your *main.js* file.

```
/** Appointment Scheduler in Library Card */
app.component('prmAccountOverviewAfter', {
  bindings: {parentCtrl: '<'},
  template: `<primo-studio-appointment-scheduler 
    parent-ctrl="$ctrl.parentCtrl"
    i18n='{
      en: {
        appointments: "Library Appointments"
      },
      fr: {
        appointments: "Rendez-vous à la bibliothèque"
      }
    }'
  ></primo-studio-appointment-scheduler>`
});
/** END Appointment Scheduler in Library Card */

Let us know if that works for you.

**Comment by bibnumbcu** [comment]
Thank you it's ok
